Repository olbrich/ruby-units, pull requests merged in 2021-11, with the labels that each got.

#242 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#243 Update dependencies
  Gemfile.lock
Labels: maintenance

#241 Replace fixed class method calls with self(.class) in Unit class
  lib/ruby_units/unit.rb
Labels: feature request, Minor

#216 Resolution appears to be lost when coverting bytes to GiB
  Gemfile.lock
  lib/ruby_units/unit.rb
  spec/ruby_units/unit_spec.rb
Labels: bug, confirmed, Minor

#244 Inches: anything not between -9 and 9 parses incorrectly
  lib/ruby_units/configuration.rb
  lib/ruby_units/definition.rb
  lib/ruby_units/unit.rb
  spec/ruby_units/unit_spec.rb
Labels: bug, Patch

#246 Improve documentation and argument passing for `round`, `truncate`, `ceil` and `floor`
  lib/ruby_units/unit.rb
  spec/ruby_units/unit_spec.rb
Labels: bug

#247 Remove `chunk_while` workaround for old jruby
  lib/ruby_units/unit.rb
Labels: maintenance, Patch

#248 Eliminate terms instance method
  lib/ruby_units/unit.rb
  spec/ruby_units/unit_spec.rb
Labels: feature request, Minor
