Repository olbrich/ruby-units, pull requests merged in 2022-10, with the labels that each got.

#266 Use module prepend
  .tool-versions
  CHANGELOG.txt
  Gemfile.lock
  lib/ruby_units/array.rb
  lib/ruby_units/date.rb
  lib/ruby_units/math.rb
  lib/ruby_units/numeric.rb
  lib/ruby_units/string.rb
  lib/ruby_units/time.rb
  lib/ruby_units/unit.rb
  lib/ruby_units/version.rb
  spec/ruby_units/array_spec.rb
  spec/ruby_units/complex_spec.rb
  spec/ruby_units/date_spec.rb
  spec/ruby_units/math_spec.rb
  spec/ruby_units/numeric_spec.rb
  spec/ruby_units/range_spec.rb
  spec/ruby_units/string_spec.rb
  spec/ruby_units/temperature_spec.rb
  spec/ruby_units/time_spec.rb
  spec/ruby_units/unit_spec.rb
  spec/spec_helper.rb
Labels: Major

#271 Refactor caching
  .github/workflows/codeql-analysis.yml
  .solargraph.yml
  Gemfile.lock
  lib/ruby_units/cache.rb
  lib/ruby_units/configuration.rb
  lib/ruby_units/unit.rb
  spec/ruby_units/cache_spec.rb
  spec/ruby_units/unit_spec.rb
Labels: maintenance, Patch

#273 Insert documentation about format+convert
  README.md
Labels: Patch
